services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - rh-network
  
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
        sleep 30;
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Passw0rd -i /init.sql
      "
    networks:
      - rh-network

  api:
    build:
      context: .
      dockerfile: ./Rh-Backend/Dockerfile
    container_name: rh-backend
    ports:
      - "5234:5234"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=Server=sqlserver;Database=Rh;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - rh-network

networks:
  rh-network:
    driver: bridge
